#!/bin/bash
set -e

if [ -n "$DEBUG" ]; then
  echo -e "\n### DEBUG ###"
  env
  echo -e "### DEBUG ###\n"
fi

# Firefox specific environment variables
# https://github.com/AppImage/pkg2appimage/commit/c9b09eb557b6b0b4d914ecb82998148f38880d1d
export SNAP_NAME="firefox"
# export MOZ_LEGACY_PROFILES=1

THIS="$0"
# http://stackoverflow.com/questions/3190818/
args=("$@")
NUMBER_OF_ARGS="$#"

if [ -z "$APPDIR" ]; then
  # Find the AppDir. It is the directory that contains AppRun.
  # This assumes that this script resides inside the AppDir or a subdirectory.
  # If this script is run inside an AppImage, then the AppImage runtime likely has already set $APPDIR
  path="$(dirname "$(readlink -f "${THIS}")")"
  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
    path=${path%/*}
  done
  export APPDIR="$path"
fi

export PATH="${APPDIR}:${APPDIR}/usr/bin:${APPDIR}/usr/sbin:${APPDIR}/bin:${APPDIR}/sbin/${PATH:+:$PATH}"
export XDG_DATA_DIRS="./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:${XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas:${GSETTINGS_SCHEMA_DIR}"

if [ -n "$DEBUG" ]; then
  echo -e "\n### DEBUG ###"
  echo "APPDIR=${APPDIR}"
  echo "PATH=${PATH}"
  echo "XDG_DATA_DIRS=${XDG_DATA_DIRS}"
  echo "GSETTINGS_SCHEMA_DIR=${GSETTINGS_SCHEMA_DIR}"  
  echo -e "### DEBUG ###\n"
fi

BIN="$APPDIR/FIREFOX_BIN_FILE"

if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ]; then
  trap atexit EXIT
fi

isEulaAccepted=1
atexit() {
  if [ $isEulaAccepted == 1 ]; then
    if [ $NUMBER_OF_ARGS -eq 0 ]; then
      exec "$BIN"
    else
      exec "$BIN" "${args[@]}"
    fi
  fi
}

if [ -z "$APPIMAGE" ]; then
  APPIMAGE="$APPDIR/AppRun"
  # not running from within an AppImage; hence using the AppRun for Exec=
fi
